# Generated by Django 6.0.6 on 2026-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitudeM', models.FloatField(default=0)),
            ],
        ),
    ]
