# Generated by Django 6.0.6 on 2026-06-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satellites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('epoch', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satellites.satellite')),
            ],
        ),
    ]
