# Generated by Django 6.0.6 on 2026-06-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groundstations', '0001_initial'),
        ('satellites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Complete', 'Complete'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('ground_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundstations.groundstation')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satellites.satellite')),
            ],
        ),
    ]
