# Generated by Django 6.0.6 on 2026-06-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('norad_id', models.IntegerField(unique=True)),
                ('uplink_freq', models.FloatField(blank=True, null=True)),
                ('downlink_freq', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
