# Generated by Django 6.0.6 on 2026-06-29 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='downlink_freq',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='uplink_freq',
        ),
        migrations.AddField(
            model_name='satellite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle_line1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle_line2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='norad_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
