# Generated by Django 6.0.6 on 2026-06-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0002_remove_satellite_downlink_freq_remove_satellite_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='tle_line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='tle_line2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
